version: "3.9"
services:
  app:
    build: .
    # command: poetry run flask run -h 0.0.0.0
    command: ./start_server.sh
    restart: always
    volumes:
      - ${HOME}/.ssh:/root/.ssh
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT}:5000
    depends_on:
      - db

  java:
    image: amazoncorretto:8
    volumes:
      - ./:/app
    command: java -jar /app/java/kreditor-1.0.0.jar
    ports:
      - 127.0.0.1:${JAVA_LOCAL_PORT}:8080

  db:
    image: postgres:12
    restart: always
    volumes:
      - ./:/app
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=${DB_USER-postgres}
    ports:
      - 127.0.0.1:${DB_LOCAL_PORT}:5432

volumes:
  db_data: