"""transaction_foreign_keys

Revision ID: 028fbf789e91
Revises: 9cb23c8c9d67
Create Date: 2022-05-16 11:05:33.789071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028fbf789e91'
down_revision = '9cb23c8c9d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transactions', 'users', ['admin_id'], ['id'])
    op.drop_column('transactions', 'admin_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('admin_username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    # ### end Alembic commands ###
