"""empty message

Revision ID: 21a434406e6c
Revises: 
Create Date: 2022-03-30 17:01:02.358910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a434406e6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('instance', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reseller', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['reseller'], ['user.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('billing',
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('reseller', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reseller'], ['user.id'], ),
    sa.PrimaryKeyConstraint('reseller_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('history')
    # ### end Alembic commands ###
