"""empty message

Revision ID: 383bb315f870
Revises: cad588e3f32d
Create Date: 2022-04-19 10:49:26.524360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383bb315f870'
down_revision = 'cad588e3f32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
