"""billing_qrcode

Revision ID: 56a15b2c6277
Revises: 581385dd1c80
Create Date: 2022-04-26 11:00:23.249053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a15b2c6277'
down_revision = '581385dd1c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('qrcode', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'qrcode')
    # ### end Alembic commands ###
