"""account_deleted

Revision ID: 581385dd1c80
Revises: 5d4e422e86e3
Create Date: 2022-04-22 11:36:12.489604

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "581385dd1c80"
down_revision = "5d4e422e86e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("deleted", sa.Boolean(), server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "deleted")
    # ### end Alembic commands ###
