"""account_publoc_key

Revision ID: 6c5be3309eca
Revises: 56a15b2c6277
Create Date: 2022-05-02 07:59:41.403282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5be3309eca'
down_revision = '56a15b2c6277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'public_key')
    # ### end Alembic commands ###
