"""fix

Revision ID: 8cc79e970a06
Revises: 6c5be3309eca
Create Date: 2022-05-05 13:07:43.969324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc79e970a06'
down_revision = '6c5be3309eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billings', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billings', type_='foreignkey')
    op.drop_column('billings', 'account_id')
    # ### end Alembic commands ###
