"""transactions

Revision ID: 9cb23c8c9d67
Revises: 9e71a9d97ada
Create Date: 2022-05-16 09:11:38.564859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb23c8c9d67'
down_revision = '9e71a9d97ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('deposit', 'withdraw', name='action'), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_username', sa.String(length=64), nullable=True),
    sa.Column('transaction_amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
