"""user_credit_allowed

Revision ID: 9e71a9d97ada
Revises: e034f7180d63
Create Date: 2022-05-13 11:40:57.730679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e71a9d97ada'
down_revision = 'e034f7180d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit_alowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credit_alowed')
    # ### end Alembic commands ###
