"""billing_cost

Revision ID: e034f7180d63
Revises: e1748ec7f424
Create Date: 2022-05-12 17:42:36.485181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e034f7180d63'
down_revision = 'e1748ec7f424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billings', 'cost')
    # ### end Alembic commands ###
