"""user_credits

Revision ID: e1748ec7f424
Revises: 8cc79e970a06
Create Date: 2022-05-12 12:57:04.760160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1748ec7f424'
down_revision = '8cc79e970a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits_available', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('package_500_cost', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('package_1000_cost', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('package_1500_cost', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('package_2500_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'package_2500_cost')
    op.drop_column('users', 'package_1500_cost')
    op.drop_column('users', 'package_1000_cost')
    op.drop_column('users', 'package_500_cost')
    op.drop_column('users', 'credits_available')
    # ### end Alembic commands ###
